# -*- coding: utf-8 -*-
"""AI LAYOFFS .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPYyZYICt0aj-ykXS6-Mr5ZTo9Z380Yu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/tech_layoffs_2026_tracker.csv")

df.head()

df.shape

df.columns

df.info()

df.isnull().sum()

df.describe()

df.duplicated().sum()

df['layoff_date'] = pd.to_datetime(df['layoff_date'])

df.dtypes

top_companies = df[['company', 'jobs_cut']].sort_values(by='jobs_cut', ascending=False)
top_companies.head(10)

top10 = top_companies.head(10)
plt.figure(figsize=(12,6))
sns.barplot(x='company', y='jobs_cut', data=top10)
plt.title("Top 10 Companies by Layoffs")
plt.xlabel("Company")
plt.ylabel("Jobs Cut")
plt.xticks(rotation=45)
plt.show()

df['ai_cited'].value_counts()

plt.figure(figsize=(6,5))
sns.countplot(x='ai_cited', data=df)
plt.title("AI-Cited vs Non-AI Layoffs")
plt.xlabel("AI Cited")
plt.ylabel("Count")
plt.show()

sector_layoffs = df.groupby('sector')['jobs_cut'].sum().sort_values(ascending=False)
sector_layoffs

plt.figure(figsize=(14,7))
sector_layoffs.plot(kind='bar')
plt.title("Total Layoffs by Sector")
plt.xlabel("Sector")
plt.ylabel("Total Jobs Cut")
plt.xticks(rotation=60, ha='right')
plt.tight_layout()
plt.show()

layoffs_over_time = df.groupby('layoff_date')['jobs_cut'].sum()
layoffs_over_time

plt.figure(figsize=(14,6))
plt.plot(layoffs_over_time.index, layoffs_over_time.values)
plt.title("Layoff Trends Over Time")
plt.xlabel("Date")
plt.ylabel("Total Jobs Cut")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

numeric_df = df.select_dtypes(include=['int64', 'float64'])
correlation_matrix = numeric_df.corr()
correlation_matrix

plt.figure(figsize=(12,8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error: {mae:.2f}")
print(f"R-squared: {r2:.2f}")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel("Actual Jobs Cut")
plt.ylabel("Predicted Jobs Cut")
plt.title("Actual vs. Predicted Jobs Cut")
plt.grid(True)
plt.show()

from sklearn.ensemble import RandomForestRegressor
pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),
                              ('regressor', RandomForestRegressor(random_state=42))])
pipeline_rf.fit(X_train, y_train)
y_pred_rf = pipeline_rf.predict(X_test)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)
print(f"Random Forest Mean Absolute Error: {mae_rf:.2f}")
print(f"Random Forest R-squared: {r2_rf:.2f}")

plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred_rf, alpha=1.0, s=100)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel("Actual Jobs Cut")
plt.ylabel("Predicted Jobs Cut")
plt.title("Actual vs. Predicted Jobs Cut")
plt.grid(True)
plt.show()

import joblib
joblib.dump(model, 'model.pkl')